### ISSUE TITLE
Broken URLs

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#2119]
Some URLs are broken, see https://github.com/OWASP/owasp-mstg/runs/6897262028?check_suite_focus=true

Search for [✖] in the log below.

- If you are able to open the link you may need to add an exception in https://github.com/OWASP/owasp-mstg/blob/master/.github/workflows/config/mlc_config.json
- If the link does not lead anywhere anymore you can search the web archive and see if you can find the same page
- Else we usually modify the text to avoid that link
- This one “https://github.com/b-mueller” can be replaced with the twitter profile: https://twitter.com/muellerberndt

```bash
=========================> MARKDOWN LINK CHECK <=========================
FILE: ./CODE_OF_CONDUCT.md
5 links checked.
FILE: ./tools/docker/README.md
2 links checked.
FILE: ./tools/README.md
[✖] https://github.com/sushi2k/owasp-mstg → Status: 404
8 links checked.
ERROR: 1 dead links found!
[✖] https://github.com/sushi2k/owasp-mstg → Status: 404
FILE: ./CONTRIBUTING.md
[✖] https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/incorporating-feedback-in-your-pull-request → Status: 403
[✖] https://help.github.com/en/articles/signing-up-for-a-new-github-account → Status: 403
[✖] https://help.github.com/en/articles/fork-a-repo → Status: 403
[✖] https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork → Status: 403
15 links checked.
ERROR: 4 dead links found!
[✖] https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/incorporating-feedback-in-your-pull-request → Status: 403
[✖] https://help.github.com/en/articles/signing-up-for-a-new-github-account → Status: 403
[✖] https://help.github.com/en/articles/fork-a-repo → Status: 403
[✖] https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork → Status: 403
FILE: ./CHANGELOG.md
4 links checked.
FILE: ./Document/0x04e-Testing-Authentication-and-Session-Management.md
49 links checked.
FILE: ./Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md
51 links checked.
FILE: ./Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
49 links checked.
FILE: ./Document/0x06f-Testing-Local-Authentication.md
9 links checked.
FILE: ./Document/0x06h-Testing-Platform-Interaction.md
[✖] https://www.apple.com/.well-known/apple-app-site-association → Status: 404
[✖] https://academy.realm.io/posts/tim-oliver-realm-cocoa-tutorial-on-encryption-with-realm/ → Status: 404
218 links checked.
ERROR: 2 dead links found!
[✖] https://www.apple.com/.well-known/apple-app-site-association → Status: 404
[✖] https://academy.realm.io/posts/tim-oliver-realm-cocoa-tutorial-on-encryption-with-realm/ → Status: 404
FILE: ./Document/0x04c-Tampering-and-Reverse-Engineering.md
[✖] https://triton.quarkslab.com/files/csaw2016-sos-rthomas-jsalwan.pdf → Status: 404
10 links checked.
ERROR: 1 dead links found!
[✖] https://triton.quarkslab.com/files/csaw2016-sos-rthomas-jsalwan.pdf → Status: 404
FILE: ./Document/0x07-Appendix.md
0 links checked.
FILE: ./Document/CHANGELOG.md
4 links checked.
FILE: ./Document/0x05b-Basic-Security_Testing.md
90 links checked.
FILE: ./Document/0x04f-Testing-Network-Communication.md
75 links checked.
FILE: ./Document/0x04b-Mobile-App-Security-Testing.md
18 links checked.
FILE: ./Document/0x06d-Testing-Data-Storage.md
64 links checked.
FILE: ./Document/0x05i-Testing-Code-Quality-and-Build-Settings.md
32 links checked.
FILE: ./Document/0x06a-Platform-Overview.md
25 links checked.
FILE: ./Document/0x04i-Testing-User-Privacy-Protection.md
[✖] https://www.researchgate.net/publication/339349349_Engineering_Privacy_in_Smartphone_Apps_A_Technical_Guideline_Catalog_for_App_Developers → Status: 403
24 links checked.
ERROR: 1 dead links found!
[✖] https://www.researchgate.net/publication/339349349_Engineering_Privacy_in_Smartphone_Apps_A_Technical_Guideline_Catalog_for_App_Developers → Status: 403
FILE: ./Document/0x05h-Testing-Platform-Interaction.md
136 links checked.
FILE: ./Document/0x06e-Testing-Cryptography.md
49 links checked.
FILE: ./Document/0x04h-Testing-Code-Quality.md
14 links checked.
FILE: ./Document/0x05f-Testing-Local-Authentication.md
17 links checked.
FILE: ./Document/0x01-Foreword.md
2 links checked.
FILE: ./Document/0x06c-Reverse-Engineering-and-Tampering.md
85 links checked.
FILE: ./Document/0x03-Overview.md
6 links checked.
FILE: ./Document/0x05e-Testing-Cryptography.md
57 links checked.
FILE: ./Document/SUMMARY.md
33 links checked.
FILE: ./Document/0x06g-Testing-Network-Communication.md
35 links checked.
FILE: ./Document/0x05a-Platform-Overview.md
63 links checked.
FILE: ./Document/0x05c-Reverse-Engineering-and-Tampering.md
[✖] https://packetstormsecurity.com/files/138504/HITB_Hacking_Soft_Tokens_v1.2.pdf → Status: 0 Error: ETIMEDOUT
    at Timeout.<anonymous> (/usr/local/lib/node_modules/markdown-link-check/node_modules/request/request.js:848:19)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 'ETIMEDOUT',
  connect: true
}
119 links checked.
ERROR: 1 dead links found!
[✖] https://packetstormsecurity.com/files/138504/HITB_Hacking_Soft_Tokens_v1.2.pdf → Status: 0
FILE: ./Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
[✖] https://academy.realm.io/posts/russ-bishop-unsafe-swift/ → Status: 404
40 links checked.
ERROR: 1 dead links found!
[✖] https://academy.realm.io/posts/russ-bishop-unsafe-swift/ → Status: 404
FILE: ./Document/cover.md
0 links checked.
FILE: ./Document/0x05g-Testing-Network-Communication.md
28 links checked.
FILE: ./Document/0x04g-Testing-Cryptography.md
28 links checked.
FILE: ./Document/0x09-Suggested-Reading.md
14 links checked.
FILE: ./Document/0x06b-Basic-Security-Testing.md
73 links checked.
FILE: ./Document/0x05d-Testing-Data-Storage.md
85 links checked.
FILE: ./Document/0x08-Testing-Tools.md
[✖] http://www.manpagez.com/man/1/nm/osx-10.12.6.php → Status: 0 Error: getaddrinfo EAI_AGAIN www.manpagez.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'www.manpagez.com'
}
[✖] https://busybox.net/ → Status: 0 Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/markdown-link-check/node_modules/request/request.js:816:19)
    at Object.onceWrapper (node:events:641:28)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.emitRequestTimeout (node:_http_client:771:9)
    at Object.onceWrapper (node:events:641:28)
    at TLSSocket.emit (node:events:539:35)
    at TLSSocket.Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 'ESOCKETTIMEDOUT',
  connect: false
}
[✖] https://busybox.net/FAQ.html#getting_started → Status: 0 Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/markdown-link-check/node_modules/request/request.js:816:19)
    at Object.onceWrapper (node:events:641:28)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.emitRequestTimeout (node:_http_client:771:9)
    at Object.onceWrapper (node:events:641:28)
    at TLSSocket.emit (node:events:539:35)
    at TLSSocket.Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 'ESOCKETTIMEDOUT',
  connect: false
}
211 links checked.
ERROR: 3 dead links found!
[✖] http://www.manpagez.com/man/1/nm/osx-10.12.6.php → Status: 0
[✖] https://busybox.net/ → Status: 0
[✖] https://busybox.net/FAQ.html#getting_started → Status: 0
FILE: ./Document/0x02-Frontispiece.md
13 links checked.
FILE: ./Document/metadata.md
1 links checked.
FILE: ./Document/0x02b-MASVS-MSTG-Adoption.md
21 links checked.
FILE: ./Document/0x04a-Mobile-App-Taxonomy.md
13 links checked.
FILE: ./License.md
5 links checked.
FILE: ./PULL_REQUEST_TEMPLATE.md
0 links checked.
FILE: ./style_guide.md
1 links checked.
FILE: ./Crackmes/README.md
[✖] https://github.com/b-mueller → Status: 404
38 links checked.
ERROR: 1 dead links found!
[✖] https://github.com/b-mueller → Status: 404
FILE: ./Samples/Android/02_CertificatePinning/readme.md
0 links checked.
FILE: ./Templates/testcase.md
1 links checked.
FILE: ./README.md
68 links checked.
```

**Comment by wwwhackcom** [comment]
Hi @sushi2k and @cpholguera, I am a new contributor, it was nice meeting Sven there during the OWAPS NZ Day. Shall I start with this issue, please let me know, thank you.
